
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">

    <title>Solicitud de Servicio Protección Ejecutiva</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="starter-template.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <style>

  ul.ui-autocomplete {
    z-index: 1100;
}

body {
  background-image: url("{{ asset('/img/command.jpg') }}");
  background-repeat: no-repeat;
  background-size: cover;
  background-color: #cccccc;
}

</style>



  <body >


    

    

    <div class="container">


    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <button class="btn-default pull-right">Cerrar</button>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

           <nav class="navbar-header">
      <div class="container">
        <h1><img src="{{ asset('/img/logoot.jpg') }}"> Bienvenido, <b>{{Auth::user()->name}}</b></h1>


        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <li><a href="{{route('solicitudcliente.index')}}" class="btn btn-info"><i class="fa fa-user-secret" aria-hidden="true"></i> <span>Listado de Servicios</span></a></li
         </div>

        
      </div>
    </nav>
        
      </div>
    </div>
     <div class="row">
       <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        

        
       </div>

    

       <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">

        <div class="panel panel-primary">
  <div class="panel-primary">
   <!--  <h3 class="panel-title">Solicitud servicio Adicional</h3> -->
  </div>
  <div class="panel-body">
         {!! Form::open(['route' => 'solicitudcliente.store', 'method'=>'POST','id'=>'reg_form9']) !!}
    <legend>SERVICIO ADICIONAL PROTECCION EJECUTIVA</legend>


    <div class="form-group">
      
        <input type="hidden" class="form-control" name="id"  id="id" placeholder="Id" readonly="readonly">
        <input type="hidden" class="form-control" name="estadoservicio_id"  id="id" placeholder="Id" readonly="readonly" value="1">
    </div>




<div class="form-group">
        <label for="id">Seleccione su empresa (*)</label>
        {!! Form::select('cliente',$cliente, $clientes->id, ['class' => 'form-control','name'=>'cliente','required','placeholder' => 'Seleccione su Empresa']) !!}
    </div>


<div class="form-group">
        <label for="id">Digite el Nombre y Apellidos que realiza la solicitud (*)</label>
        <input type="text" class="form-control" name="solicitante_interno2"  id="solicitante_interno2" placeholder="Digite el Nombre y Apellidos que realiza la solicitud", required>
</div>

    {{-- <div class="form-group">
        <label for="id">fecha_inicio_servicio</label>
        <input type="date" class="form-control" name="fecha_inicio_servicio"  id="fecha_inicio_servicio" placeholder="Número orden de sercivios">
    </div> --}}


<div class="form-group">
        <label for="id">Digite la Ciudad donde se prestará el servicio (*)</label>
        <input type="text" class="form-control" name="ciudad_destino"  id="ciudad_destino3" placeholder="ciudad_destino" value="BOGOTA, D.C." required>
    </div>

 @php

        $hoy = date("Y-m-d H:i:s");
    //echo $hoy;

 @endphp



<div class="form-group">
        
        <input type="hidden" class="form-control" name="fecha_solicitud"  id="fecha_solicitud" placeholder="fecha_solicitud" value="<?php $date = new DateTime();
echo $date->format('Y-m-d\TH:i'); ?>" >
    </div>

  @php

    $sino= array ("SI","NO");

  @endphp

   <div class="form-group">

    <label for="id">Requiere el Escolta Bilingue? (*)</label>

   <select name="bilingue"  class="form-control" required="required" placeholder = "Seleccionar">
     <option value="SI">Si</option>
     <option value="NO">No</option>
   </select>
   
  </div>

     <div class="form-group">

    <label for="id">Que Arma requiere? (*)</label>


   {!! Form::select('arma_id', $armas, null, ['class'=>'form-control', 'placeholder' => 'Seleccionar el arma', 'required']) !!}
  </div>

  <div class="form-group">

    <label for="id">Qué tipo de Vehículo requiere? (*)</label>
  {!! Form::select('tipo', $tipodevehiculo, null, ['class' => 'form-control','placeholder' => 'Seleccionar tipo de Vehículo', 'required']) !!}

</div>

<div class="form-group">
    <label for="id">Qué tipo de Servicio? (*)</label>

    {!! Form::select('tipo_de_servicio', $tiposervicio, null, ['class' => 'form-control', 'placeholder' => 'Seleccione el Tipo de Servicio', 'required']) !!}

  </div>



<div class="form-group">
        <label for="id">Seleccione la Fecha y Hora que necesita el servicio</label>
        <input type="datetime-local" class="form-control" name="fecha_inicio_servicio"  id="fecha_inicio_servicio" placeholder="fecha_inicio_servicio" value="<?php $date = new DateTime();
echo $date->format('Y-m-d\TH:i'); ?>">
</div>

<div class="form-group">
        <label for="id">Seleccione la Fecha Final y Hora</label>
        <input type="datetime-local" class="form-control" name="fecha_final_servicio"  id="fecha_final_servicio" placeholder="fecha_final_servicio" value="<?php $date = new DateTime();
echo $date->format('Y-m-d\T23:59'); ?>">
</div>    

<div class="form-group">
        <label for="id">Detalle solicitud del servicio</label>
        <textarea cols="75" rows="3" id="detalle_del_servicio" name="detalle_del_servicio" placeholder="Colocar el detalle que necesita, para su servicio" required class="form-control"></textarea>
    </div>

<input type="hidden" class="form-control" name="users_id"  id="users_id" placeholder=""
value="{{Auth::user()->id}}">


 
    <button type="submit" class="btn btn-large btn-block btn-primary">Enviar Solicitud a Omnitempus</button>  
  

{!! Form::close() !!}
          </div>
</div>

       </div>
     </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>





    <script type="text/javascript">

   
      
    $( function() {
    var availableTags = [
     "MEDELLIN",
"ABEJORRAL",
"ABRIAQUI",
"ALEJANDRIA",
"AMAGA",
"AMALFI",
"ANDES",
"ANGELOPOLIS",
"ANGOSTURA",
"ANORI",
"SANTAFE DE ANTIOQUIA",
"ANZA",
"APARTADO",
"ARBOLETES",
"ARGELIA",
"ARMENIA",
"BARBOSA",
"BELMIRA",
"BELLO",
"BETANIA",
"BETULIA",
"CIUDAD BOLIVAR",
"BRICEÑO",
"BURITICA",
"CACERES",
"CAICEDO",
"CALDAS",
"CAMPAMENTO",
"CAÑASGORDAS",
"CARACOLI",
"CARAMANTA",
"CAREPA",
"EL CARMEN DE VIBORAL",
"CAROLINA",
"CAUCASIA",
"CHIGORODO",
"CISNEROS",
"COCORNA",
"CONCEPCION",
"CONCORDIA",
"COPACABANA",
"DABEIBA",
"DON MATIAS",
"EBEJICO",
"EL BAGRE",
"ENTRERRIOS",
"ENVIGADO",
"FREDONIA",
"FRONTINO",
"GIRALDO",
"GIRARDOTA",
"GOMEZ PLATA",
"GRANADA",
"GUADALUPE",
"GUARNE",
"GUATAPE",
"HELICONIA",
"HISPANIA",
"ITAGUI",
"ITUANGO",
"JARDIN",
"JERICO",
"LA CEJA",
"LA ESTRELLA",
"LA PINTADA",
"LA UNION",
"LIBORINA",
"MACEO",
"MARINILLA",
"MONTEBELLO",
"MURINDO",
"MUTATA",
"NARIÑO",
"NECOCLI",
"NECHI",
"OLAYA",
"PEÐOL",
"PEQUE",
"PUEBLORRICO",
"PUERTO BERRIO",
"PUERTO NARE",
"PUERTO TRIUNFO",
"REMEDIOS",
"RETIRO",
"RIONEGRO",
"SABANALARGA",
"SABANETA",
"SALGAR",
"SAN ANDRES DE CUERQUIA",
"SAN CARLOS",
"SAN FRANCISCO",
"SAN JERONIMO",
"SAN JOSE DE LA MONTAÑA",
"SAN JUAN DE URABA",
"SAN LUIS",
"SAN PEDRO",
"SAN PEDRO DE URABA",
"SAN RAFAEL",
"SAN ROQUE",
"SAN VICENTE",
"SANTA BARBARA",
"SANTA ROSA DE OSOS",
"SANTO DOMINGO",
"EL SANTUARIO",
"SEGOVIA",
"SONSON",
"SOPETRAN",
"TAMESIS",
"TARAZA",
"TARSO",
"TITIRIBI",
"TOLEDO",
"TURBO",
"URAMITA",
"URRAO",
"VALDIVIA",
"VALPARAISO",
"VEGACHI",
"VENECIA",
"VIGIA DEL FUERTE",
"YALI",
"YARUMAL",
"YOLOMBO",
"YONDO",
"ZARAGOZA",
"BARRANQUILLA",
"BARANOA",
"CAMPO DE LA CRUZ",
"CANDELARIA",
"GALAPA",
"JUAN DE ACOSTA",
"LURUACO",
"MALAMBO",
"MANATI",
"PALMAR DE VARELA",
"PIOJO",
"POLONUEVO",
"PONEDERA",
"PUERTO COLOMBIA",
"REPELON",
"SABANAGRANDE",
"SABANALARGA",
"SANTA LUCIA",
"SANTO TOMAS",
"SOLEDAD",
"SUAN",
"TUBARA",
"USIACURI",
"BOGOTA, D.C.",
"CARTAGENA",
"ACHI",
"ALTOS DEL ROSARIO",
"ARENAL",
"ARJONA",
"ARROYOHONDO",
"BARRANCO DE LOBA",
"CALAMAR",
"CANTAGALLO",
"CICUCO",
"CORDOBA",
"CLEMENCIA",
"EL CARMEN DE BOLIVAR",
"EL GUAMO",
"EL PEÑON",
"HATILLO DE LOBA",
"MAGANGUE",
"MAHATES",
"MARGARITA",
"MARIA LA BAJA",
"MONTECRISTO",
"MOMPOS",
"NOROSI",
"MORALES",
"PINILLOS",
"REGIDOR",
"RIO VIEJO",
"SAN CRISTOBAL",
"SAN ESTANISLAO",
"SAN FERNANDO",
"SAN JACINTO",
"SAN JACINTO DEL CAUCA",
"SAN JUAN NEPOMUCENO",
"SAN MARTIN DE LOBA",
"SAN PABLO",
"SANTA CATALINA",
"SANTA ROSA",
"SANTA ROSA DEL SUR",
"SIMITI",
"SOPLAVIENTO",
"TALAIGUA NUEVO",
"TIQUISIO",
"TURBACO",
"TURBANA",
"VILLANUEVA",
"ZAMBRANO",
"TUNJA",
"ALMEIDA",
"AQUITANIA",
"ARCABUCO",
"BELEN",
"BERBEO",
"BETEITIVA",
"BOAVITA",
"BOYACA",
"BRICEÑO",
"BUENAVISTA",
"BUSBANZA",
"CALDAS",
"CAMPOHERMOSO",
"CERINZA",
"CHINAVITA",
"CHIQUINQUIRA",
"CHISCAS",
"CHITA",
"CHITARAQUE",
"CHIVATA",
"CIENEGA",
"COMBITA",
"COPER",
"CORRALES",
"COVARACHIA",
"CUBARA",
"CUCAITA",
"CUITIVA",
"CHIQUIZA",
"CHIVOR",
"DUITAMA",
"EL COCUY",
"EL ESPINO",
"FIRAVITOBA",
"FLORESTA",
"GACHANTIVA",
"GAMEZA",
"GARAGOA",
"GUACAMAYAS",
"GUATEQUE",
"GUAYATA",
"GsICAN",
"IZA",
"JENESANO",
"JERICO",
"LABRANZAGRANDE",
"LA CAPILLA",
"LA VICTORIA",
"LA UVITA",
"VILLA DE LEYVA",
"MACANAL",
"MARIPI",
"MIRAFLORES",
"MONGUA",
"MONGUI",
"MONIQUIRA",
"MOTAVITA",
"MUZO",
"NOBSA",
"NUEVO COLON",
"OICATA",
"OTANCHE",
"PACHAVITA",
"PAEZ",
"PAIPA",
"PAJARITO",
"PANQUEBA",
"PAUNA",
"PAYA",
"PAZ DE RIO",
"PESCA",
"PISBA",
"PUERTO BOYACA",
"QUIPAMA",
"RAMIRIQUI",
"RAQUIRA",
"RONDON",
"SABOYA",
"SACHICA",
"SAMACA",
"SAN EDUARDO",
"SAN JOSE DE PARE",
"SAN LUIS DE GACENO",
"SAN MATEO",
"SAN MIGUEL DE SEMA",
"SAN PABLO DE BORBUR",
"SANTANA",
"SANTA MARIA",
"SANTA ROSA DE VITERBO",
"SANTA SOFIA",
"SATIVANORTE",
"SATIVASUR",
"SIACHOQUE",
"SOATA",
"SOCOTA",
"SOCHA",
"SOGAMOSO",
"SOMONDOCO",
"SORA",
"SOTAQUIRA",
"SORACA",
"SUSACON",
"SUTAMARCHAN",
"SUTATENZA",
"TASCO",
"TENZA",
"TIBANA",
"TIBASOSA",
"TINJACA",
"TIPACOQUE",
"TOCA",
"TOGsI",
"TOPAGA",
"TOTA",
"TUNUNGUA",
"TURMEQUE",
"TUTA",
"TUTAZA",
"UMBITA",
"VENTAQUEMADA",
"VIRACACHA",
"ZETAQUIRA",
"MANIZALES",
"AGUADAS",
"ANSERMA",
"ARANZAZU",
"BELALCAZAR",
"CHINCHINA",
"FILADELFIA",
"LA DORADA",
"LA MERCED",
"MANZANARES",
"MARMATO",
"MARQUETALIA",
"MARULANDA",
"NEIRA",
"NORCASIA",
"PACORA",
"PALESTINA",
"PENSILVANIA",
"RIOSUCIO",
"RISARALDA",
"SALAMINA",
"SAMANA",
"SAN JOSE",
"SUPIA",
"VICTORIA",
"VILLAMARIA",
"VITERBO",
"FLORENCIA",
"ALBANIA",
"BELEN DE LOS ANDAQUIES",
"CARTAGENA DEL CHAIRA",
"CURILLO",
"EL DONCELLO",
"EL PAUJIL",
"LA MONTAÑITA",
"MILAN",
"MORELIA",
"PUERTO RICO",
"SAN JOSE DEL FRAGUA",
"SAN VICENTE DEL CAGUAN",
"SOLANO",
"SOLITA",
"VALPARAISO",
"POPAYAN",
"ALMAGUER",
"ARGELIA",
"BALBOA",
"BOLIVAR",
"BUENOS AIRES",
"CAJIBIO",
"CALDONO",
"CALOTO",
"CORINTO",
"EL TAMBO",
"FLORENCIA",
"GUACHENE",
"GUAPI",
"INZA",
"JAMBALO",
"LA SIERRA",
"LA VEGA",
"LOPEZ",
"MERCADERES",
"MIRANDA",
"MORALES",
"PADILLA",
"PAEZ",
"PATIA",
"PIAMONTE",
"PIENDAMO",
"PUERTO TEJADA",
"PURACE",
"ROSAS",
"SAN SEBASTIAN",
"SANTANDER DE QUILICHAO",
"SANTA ROSA",
"SILVIA",
"SOTARA",
"SUAREZ",
"SUCRE",
"TIMBIO",
"TIMBIQUI",
"TORIBIO",
"TOTORO",
"VILLA RICA",
"VALLEDUPAR",
"AGUACHICA",
"AGUSTIN CODAZZI",
"ASTREA",
"BECERRIL",
"BOSCONIA",
"CHIMICHAGUA",
"CHIRIGUANA",
"CURUMANI",
"EL COPEY",
"EL PASO",
"GAMARRA",
"GONZALEZ",
"LA GLORIA",
"LA JAGUA DE IBIRICO",
"MANAURE",
"PAILITAS",
"PELAYA",
"PUEBLO BELLO",
"RIO DE ORO",
"LA PAZ",
"SAN ALBERTO",
"SAN DIEGO",
"SAN MARTIN",
"TAMALAMEQUE",
"MONTERIA",
"AYAPEL",
"BUENAVISTA",
"CANALETE",
"CERETE",
"CHIMA",
"CHINU",
"CIENAGA DE ORO",
"COTORRA",
"LA APARTADA",
"LORICA",
"LOS CORDOBAS",
"MOMIL",
"MONTELIBANO",
"MOÑITOS",
"PLANETA RICA",
"PUEBLO NUEVO",
"PUERTO ESCONDIDO",
"PUERTO LIBERTADOR",
"PURISIMA",
"SAHAGUN",
"SAN ANDRES SOTAVENTO",
"SAN ANTERO",
"SAN BERNARDO DEL VIENTO",
"SAN CARLOS",
"SAN PELAYO",
"TIERRALTA",
"VALENCIA",
"AGUA DE DIOS",
"ALBAN",
"ANAPOIMA",
"ANOLAIMA",
"ARBELAEZ",
"BELTRAN",
"BITUIMA",
"BOJACA",
"CABRERA",
"CACHIPAY",
"CAJICA",
"CAPARRAPI",
"CAQUEZA",
"CARMEN DE CARUPA",
"CHAGUANI",
"CHIA",
"CHIPAQUE",
"CHOACHI",
"CHOCONTA",
"COGUA",
"COTA",
"CUCUNUBA",
"EL COLEGIO",
"EL PEÑON",
"EL ROSAL",
"FACATATIVA",
"FOMEQUE",
"FOSCA",
"FUNZA",
"FUQUENE",
"FUSAGASUGA",
"GACHALA",
"GACHANCIPA",
"GACHETA",
"GAMA",
"GIRARDOT",
"GRANADA",
"GUACHETA",
"GUADUAS",
"GUASCA",
"GUATAQUI",
"GUATAVITA",
"GUAYABAL DE SIQUIMA",
"GUAYABETAL",
"GUTIERREZ",
"JERUSALEN",
"JUNIN",
"LA CALERA",
"LA MESA",
"LA PALMA",
"LA PEÑA",
"LA VEGA",
"LENGUAZAQUE",
"MACHETA",
"MADRID",
"MANTA",
"MEDINA",
"MOSQUERA",
"NARIÑO",
"NEMOCON",
"NILO",
"NIMAIMA",
"NOCAIMA",
"VENECIA",
"PACHO",
"PAIME",
"PANDI",
"PARATEBUENO",
"PASCA",
"PUERTO SALGAR",
"PULI",
"QUEBRADANEGRA",
"QUETAME",
"QUIPILE",
"APULO",
"RICAURTE",
"SAN ANTONIO DEL TEQUENDAMA",
"SAN BERNARDO",
"SAN CAYETANO",
"SAN FRANCISCO",
"SAN JUAN DE RIO SECO",
"SASAIMA",
"SESQUILE",
"SIBATE",
"SILVANIA",
"SIMIJACA",
"SOACHA",
"SOPO",
"SUBACHOQUE",
"SUESCA",
"SUPATA",
"SUSA",
"SUTATAUSA",
"TABIO",
"TAUSA",
"TENA",
"TENJO",
"TIBACUY",
"TIBIRITA",
"TOCAIMA",
"TOCANCIPA",
"TOPAIPI",
"UBALA",
"UBAQUE",
"VILLA DE SAN DIEGO DE UBATE",
"UNE",
"UTICA",
"VERGARA",
"VIANI",
"VILLAGOMEZ",
"VILLAPINZON",
"VILLETA",
"VIOTA",
"YACOPI",
"ZIPACON",
"ZIPAQUIRA",
"QUIBDO",
"ACANDI",
"ALTO BAUDO",
"ATRATO",
"BAGADO",
"BAHIA SOLANO",
"BAJO BAUDO",
"BOJAYA",
"EL CANTON DEL SAN PABLO",
"CARMEN DEL DARIEN",
"CERTEGUI",
"CONDOTO",
"EL CARMEN DE ATRATO",
"EL LITORAL DEL SAN JUAN",
"ISTMINA",
"JURADO",
"LLORO",
"MEDIO ATRATO",
"MEDIO BAUDO",
"MEDIO SAN JUAN",
"NOVITA",
"NUQUI",
"RIO IRO",
"RIO QUITO",
"RIOSUCIO",
"SAN JOSE DEL PALMAR",
"SIPI",
"TADO",
"UNGUIA",
"UNION PANAMERICANA",
"NEIVA",
"ACEVEDO",
"AGRADO",
"AIPE",
"ALGECIRAS",
"ALTAMIRA",
"BARAYA",
"CAMPOALEGRE",
"COLOMBIA",
"ELIAS",
"GARZON",
"GIGANTE",
"GUADALUPE",
"HOBO",
"IQUIRA",
"ISNOS",
"LA ARGENTINA",
"LA PLATA",
"NATAGA",
"OPORAPA",
"PAICOL",
"PALERMO",
"PALESTINA",
"PITAL",
"PITALITO",
"RIVERA",
"SALADOBLANCO",
"SAN AGUSTIN",
"SANTA MARIA",
"SUAZA",
"TARQUI",
"TESALIA",
"TELLO",
"TERUEL",
"TIMANA",
"VILLAVIEJA",
"YAGUARA",
"RIOHACHA",
"ALBANIA",
"BARRANCAS",
"DIBULLA",
"DISTRACCION",
"EL MOLINO",
"FONSECA",
"HATONUEVO",
"LA JAGUA DEL PILAR",
"MAICAO",
"MANAURE",
"SAN JUAN DEL CESAR",
"URIBIA",
"URUMITA",
"VILLANUEVA",
"SANTA MARTA",
"ALGARROBO",
"ARACATACA",
"ARIGUANI",
"CERRO SAN ANTONIO",
"CHIBOLO",
"CIENAGA",
"CONCORDIA",
"EL BANCO",
"EL PIÑON",
"EL RETEN",
"FUNDACION",
"GUAMAL",
"NUEVA GRANADA",
"PEDRAZA",
"PIJIÑO DEL CARMEN",
"PIVIJAY",
"PLATO",
"PUEBLOVIEJO",
"REMOLINO",
"SABANAS DE SAN ANGEL",
"SALAMINA",
"SAN SEBASTIAN DE BUENAVISTA",
"SAN ZENON",
"SANTA ANA",
"SANTA BARBARA DE PINTO",
"SITIONUEVO",
"TENERIFE",
"ZAPAYAN",
"ZONA BANANERA",
"VILLAVICENCIO",
"ACACIAS",
"BARRANCA DE UPIA",
"CABUYARO",
"CASTILLA LA NUEVA",
"CUBARRAL",
"CUMARAL",
"EL CALVARIO",
"EL CASTILLO",
"EL DORADO",
"FUENTE DE ORO",
"GRANADA",
"GUAMAL",
"MAPIRIPAN",
"MESETAS",
"LA MACARENA",
"URIBE",
"LEJANIAS",
"PUERTO CONCORDIA",
"PUERTO GAITAN",
"PUERTO LOPEZ",
"PUERTO LLERAS",
"PUERTO RICO",
"RESTREPO",
"SAN CARLOS DE GUAROA",
"SAN JUAN DE ARAMA",
"SAN JUANITO",
"SAN MARTIN",
"VISTAHERMOSA",
"PASTO",
"ALBAN",
"ALDANA",
"ANCUYA",
"ARBOLEDA",
"BARBACOAS",
"BELEN",
"BUESACO",
"COLON",
"CONSACA",
"CONTADERO",
"CORDOBA",
"CUASPUD",
"CUMBAL",
"CUMBITARA",
"CHACHAGsI",
"EL CHARCO",
"EL PEÑOL",
"EL ROSARIO",
"EL TABLON DE GOMEZ",
"EL TAMBO",
"FUNES",
"GUACHUCAL",
"GUAITARILLA",
"GUALMATAN",
"ILES",
"IMUES",
"IPIALES",
"LA CRUZ",
"LA FLORIDA",
"LA LLANADA",
"LA TOLA",
"LA UNION",
"LEIVA",
"LINARES",
"LOS ANDES",
"MAGsI",
"MALLAMA",
"MOSQUERA",
"NARIÑO",
"OLAYA HERRERA",
"OSPINA",
"FRANCISCO PIZARRO",
"POLICARPA",
"POTOSI",
"PROVIDENCIA",
"PUERRES",
"PUPIALES",
"RICAURTE",
"ROBERTO PAYAN",
"SAMANIEGO",
"SANDONA",
"SAN BERNARDO",
"SAN LORENZO",
"SAN PABLO",
"SAN PEDRO DE CARTAGO",
"SANTA BARBARA",
"SANTACRUZ",
"SAPUYES",
"TAMINANGO",
"TANGUA",
"SAN ANDRES DE TUMACO",
"TUQUERRES",
"YACUANQUER",
"CUCUTA",
"ABREGO",
"ARBOLEDAS",
"BOCHALEMA",
"BUCARASICA",
"CACOTA",
"CACHIRA",
"CHINACOTA",
"CHITAGA",
"CONVENCION",
"CUCUTILLA",
"DURANIA",
"EL CARMEN",
"EL TARRA",
"EL ZULIA",
"GRAMALOTE",
"HACARI",
"HERRAN",
"LABATECA",
"LA ESPERANZA",
"LA PLAYA",
"LOS PATIOS",
"LOURDES",
"MUTISCUA",
"OCAÑA",
"PAMPLONA",
"PAMPLONITA",
"PUERTO SANTANDER",
"RAGONVALIA",
"SALAZAR",
"SAN CALIXTO",
"SAN CAYETANO",
"SANTIAGO",
"SARDINATA",
"SILOS",
"TEORAMA",
"TIBU",
"TOLEDO",
"VILLA CARO",
"VILLA DEL ROSARIO",
"ARMENIA",
"BUENAVISTA",
"CALARCA",
"CIRCASIA",
"CORDOBA",
"FILANDIA",
"GENOVA",
"LA TEBAIDA",
"MONTENEGRO",
"PIJAO",
"QUIMBAYA",
"SALENTO",
"PEREIRA",
"APIA",
"BALBOA",
"BELEN DE UMBRIA",
"DOSQUEBRADAS",
"GUATICA",
"LA CELIA",
"LA VIRGINIA",
"MARSELLA",
"MISTRATO",
"PUEBLO RICO",
"QUINCHIA",
"SANTA ROSA DE CABAL",
"SANTUARIO",
"BUCARAMANGA",
"AGUADA",
"ALBANIA",
"ARATOCA",
"BARBOSA",
"BARICHARA",
"BARRANCABERMEJA",
"BETULIA",
"BOLIVAR",
"CABRERA",
"CALIFORNIA",
"CAPITANEJO",
"CARCASI",
"CEPITA",
"CERRITO",
"CHARALA",
"CHARTA",
"CHIMA",
"CHIPATA",
"CIMITARRA",
"CONCEPCION",
"CONFINES",
"CONTRATACION",
"COROMORO",
"CURITI",
"EL CARMEN DE CHUCURI",
"EL GUACAMAYO",
"EL PEÑON",
"EL PLAYON",
"ENCINO",
"ENCISO",
"FLORIAN",
"FLORIDABLANCA",
"GALAN",
"GAMBITA",
"GIRON",
"GUACA",
"GUADALUPE",
"GUAPOTA",
"GUAVATA",
"GsEPSA",
"HATO",
"JESUS MARIA",
"JORDAN",
"LA BELLEZA",
"LANDAZURI",
"LA PAZ",
"LEBRIJA",
"LOS SANTOS",
"MACARAVITA",
"MALAGA",
"MATANZA",
"MOGOTES",
"MOLAGAVITA",
"OCAMONTE",
"OIBA",
"ONZAGA",
"PALMAR",
"PALMAS DEL SOCORRO",
"PARAMO",
"PIEDECUESTA",
"PINCHOTE",
"PUENTE NACIONAL",
"PUERTO PARRA",
"PUERTO WILCHES",
"RIONEGRO",
"SABANA DE TORRES",
"SAN ANDRES",
"SAN BENITO",
"SAN GIL",
"SAN JOAQUIN",
"SAN JOSE DE MIRANDA",
"SAN MIGUEL",
"SAN VICENTE DE CHUCURI",
"SANTA BARBARA",
"SANTA HELENA DEL OPON",
"SIMACOTA",
"SOCORRO",
"SUAITA",
"SUCRE",
"SURATA",
"TONA",
"VALLE DE SAN JOSE",
"VELEZ",
"VETAS",
"VILLANUEVA",
"ZAPATOCA",
"SINCELEJO",
"BUENAVISTA",
"CAIMITO",
"COLOSO",
"COROZAL",
"COVEÑAS",
"CHALAN",
"EL ROBLE",
"GALERAS",
"GUARANDA",
"LA UNION",
"LOS PALMITOS",
"MAJAGUAL",
"MORROA",
"OVEJAS",
"PALMITO",
"SAMPUES",
"SAN BENITO ABAD",
"SAN JUAN DE BETULIA",
"SAN MARCOS",
"SAN ONOFRE",
"SAN PEDRO",
"SAN LUIS DE SINCE",
"SUCRE",
"SANTIAGO DE TOLU",
"TOLU VIEJO",
"IBAGUE",
"ALPUJARRA",
"ALVARADO",
"AMBALEMA",
"ANZOATEGUI",
"ARMERO",
"ATACO",
"CAJAMARCA",
"CARMEN DE APICALA",
"CASABIANCA",
"CHAPARRAL",
"COELLO",
"COYAIMA",
"CUNDAY",
"DOLORES",
"ESPINAL",
"FALAN",
"FLANDES",
"FRESNO",
"GUAMO",
"HERVEO",
"HONDA",
"ICONONZO",
"LERIDA",
"LIBANO",
"MARIQUITA",
"MELGAR",
"MURILLO",
"NATAGAIMA",
"ORTEGA",
"PALOCABILDO",
"PIEDRAS",
"PLANADAS",
"PRADO",
"PURIFICACION",
"RIOBLANCO",
"RONCESVALLES",
"ROVIRA",
"SALDAÑA",
"SAN ANTONIO",
"SAN LUIS",
"SANTA ISABEL",
"SUAREZ",
"VALLE DE SAN JUAN",
"VENADILLO",
"VILLAHERMOSA",
"VILLARRICA",
"CALI",
"ALCALA",
"ANDALUCIA",
"ANSERMANUEVO",
"ARGELIA",
"BOLIVAR",
"BUENAVENTURA",
"GUADALAJARA DE BUGA",
"BUGALAGRANDE",
"CAICEDONIA",
"CALIMA",
"CANDELARIA",
"CARTAGO",
"DAGUA",
"EL AGUILA",
"EL CAIRO",
"EL CERRITO",
"EL DOVIO",
"FLORIDA",
"GINEBRA",
"GUACARI",
"JAMUNDI",
"LA CUMBRE",
"LA UNION",
"LA VICTORIA",
"OBANDO",
"PALMIRA",
"PRADERA",
"RESTREPO",
"RIOFRIO",
"ROLDANILLO",
"SAN PEDRO",
"SEVILLA",
"TORO",
"TRUJILLO",
"TULUA",
"ULLOA",
"VERSALLES",
"VIJES",
"YOTOCO",
"YUMBO",
"ZARZAL",
"ARAUCA",
"ARAUQUITA",
"CRAVO NORTE",
"FORTUL",
"PUERTO RONDON",
"SARAVENA",
"TAME",
"YOPAL",
"AGUAZUL",
"CHAMEZA",
"HATO COROZAL",
"LA SALINA",
"MANI",
"MONTERREY",
"NUNCHIA",
"OROCUE",
"PAZ DE ARIPORO",
"PORE",
"RECETOR",
"SABANALARGA",
"SACAMA",
"SAN LUIS DE PALENQUE",
"TAMARA",
"TAURAMENA",
"TRINIDAD",
"VILLANUEVA",
"MOCOA",
"COLON",
"ORITO",
"PUERTO ASIS",
"PUERTO CAICEDO",
"PUERTO GUZMAN",
"LEGUIZAMO",
"SIBUNDOY",
"SAN FRANCISCO",
"SAN MIGUEL",
"SANTIAGO",
"VALLE DEL GUAMUEZ",
"VILLAGARZON",
"SAN ANDRES",
"PROVIDENCIA",
"LETICIA",
"EL ENCANTO",
"LA CHORRERA",
"LA PEDRERA",
"LA VICTORIA",
"MIRITI - PARANA",
"PUERTO ALEGRIA",
"PUERTO ARICA",
"PUERTO NARIÑO",
"PUERTO SANTANDER",
"TARAPACA",
"INIRIDA",
"BARRANCO MINAS",
"MAPIRIPANA",
"SAN FELIPE",
"PUERTO COLOMBIA",
"LA GUADALUPE",
"CACAHUAL",
"PANA PANA",
"MORICHAL",
"SAN JOSE DEL GUAVIARE",
"CALAMAR",
"EL RETORNO",
"MIRAFLORES",
"MITU",
"CARURU",
"PACOA",
"TARAIRA",
"PAPUNAUA",
"YAVARATE",
"PUERTO CARREÑO",
"LA PRIMAVERA",
"SANTA ROSALIA",
"CUMARIBO"

    ];
 
    $( "#ciudad_destino3" ).autocomplete({
      source: availableTags
    });

  } );


    </script>
  </body>
</html>
